// Billing error codes used by server actions. This file must not use "use server".
export const BILLING_ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_PAYMENT_METHOD: "INVALID_PAYMENT_METHOD",
  INVALID_BILLING_ADDRESS: "INVALID_BILLING_ADDRESS",
  INVALID_PLAN: "INVALID_PLAN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  PLAN_DOWNGRADE_BLOCKED: "PLAN_DOWNGRADE_BLOCKED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  USAGE_LIMIT_EXCEEDED: "USAGE_LIMIT_EXCEEDED",
  DATABASE_ERROR: "DATABASE_ERROR",
  BILLING_NOT_FOUND: "BILLING_NOT_FOUND",
  UPDATE_FAILED: "UPDATE_FAILED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  CARD_DECLINED: "CARD_DECLINED",
  INVALID_CARD: "INVALID_CARD",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
} as const;


